# Generated by Django 3.0.8 on 2020-09-29 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
        ('Departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=40, null=True)),
                ('last_name', models.CharField(blank=True, max_length=40, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=6, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('driving_licence', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('temporarily suspended', 'Temporarily suspended')], max_length=25, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('widowed', 'Widowed'), ('divorced ', 'Divorced')], max_length=15, null=True)),
                ('education_degree', models.CharField(blank=True, choices=[('doctor', 'Doctor'), ('Doctor of Philosophy', 'Doctor of Philosophy'), ('Doctor of Engineering', 'Doctor of Engineering'), ('Master of Arts (M.A.)', 'Master of Arts (M.A.)'), ('Master of Business Administration (M.B.A.)', 'Master of Business Administration (M.B.A.)'), ('Master of Education (M.Ed.) ', 'Master of Education (M.Ed.) '), ('Master of Engineering (M.Eng.)', 'Master of Engineering (M.Eng.)'), ('Master of Science (M.Sc.)', 'Master of Science (M.Sc.)'), ('Bachelor of Arts', 'Bachelor of Arts'), ('Bachelor of Education', 'Bachelor of Education'), ('Bachelor of Engineering', 'Bachelor of Engineering'), ('Bachelor of Sciene', 'Bachelor of Sciene'), ('technician ', 'Technician '), ('student', 'Student ')], max_length=45, null=True)),
                ('diploma_number', models.CharField(blank=True, max_length=40, null=True)),
                ('date_of_employment', models.DateField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('profile_picture', models.ImageField(default='Employees/profiles_pictures/default.png', upload_to='Employees/profiles_pictures')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Departments.Department')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('finished', models.BooleanField(default=False)),
                ('finished_by', models.CharField(blank=True, max_length=50, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Employees.Employee')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='job_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Employees.EmployeePosition'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Departments.Department')),
                ('director_name', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Employees.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('employee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Employees.Employee')),
            ],
        ),
    ]
