# Generated by Django 3.0.8 on 2020-10-11 10:32

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['last_name']},
        ),
        migrations.AlterField(
            model_name='employee',
            name='profile_picture',
            field=django_resized.forms.ResizedImageField(crop=None, default='Employees/profiles_pictures/default.png', force_format='PNG', keep_meta=True, quality=70, size=[400, 400], upload_to='Employees/profiles_pictures'),
        ),
    ]
