from django import forms
from django.contrib.auth.models import Group

from .models import *


class CreateEmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = '__all__'
        exclude = ['user', 'email', 'first_name', 'last_name']


class EmployeeForm(forms.Form):
    employee = forms.ModelChoiceField(queryset=Employee.objects.all())


class PermissionsForm(forms.Form):
    CHOICES = (
        ('add', 'Add'),
        ('delete', 'Delete'),
    )

    employee = forms.ModelChoiceField(queryset=Employee.objects.all())
    group = forms.ModelChoiceField(queryset=Group.objects.all())
    function = forms.ChoiceField(choices=CHOICES)


class GroupForm(forms.Form):
    group = forms.ModelChoiceField(queryset=Group.objects.all())


class IndustryForm(forms.Form):
    CHOICES = (
        ('Administrative', 'Administrative'),
        ('Banking', 'Banking'),
        ('Consulting', 'Consulting'),
        ('Corporate', 'Corporate'),
        ('Human Resources', 'Human Resources'),
        ('Insurance', 'Insurance'),
        ('International Business', 'International Business'),
        ('Legal', 'Legal'),
        ('Public Relations', 'Public Relations'),
        ('Purchasing', 'Purchasing'),
        ('Sales', 'Sales'),
    )
    brand = forms.ChoiceField(choices=CHOICES)


class AdministrativeForm(forms.Form):
    CHOICES = (
        ('Administrative Assistant', 'Administrative Assistant'),
        ('Administrative Coordinator', 'Administrative Coordinator'),
        ('Administrative Director', 'Administrative Director'),
        ('Administrative Manager', 'Administrative Manager'),
        ('Administrative Services Manager', 'Administrative Services Manager'),
        ('Administrative Services Officer', 'Administrative Services Officer'),
        ('Administrative Specialist', 'Administrative Specialist'),
        ('Administrative Support Manager', 'Administrative Support Manager'),
        ('Administrative Support Supervisor', 'Administrative Support Supervisor'),
        ('Administrator', 'Administrator'),
        ('Assistant Director', 'Assistant Director'),
        ('Executive Assistant', 'Executive Assistant'),
        ('Executive Services Administrator', 'Executive Services Administrator'),
        ('Legal Secretary', 'Legal Secretary'),
        ('Medical Secretary', 'Medical Secretary'),
        ('Program Administrator', 'Program Administrator'),
        ('Program Manager', 'Program Manager'),
        ('Secretary', 'Secretary'),
        ('Senior Administrative Coordinator', 'Senior Administrative Coordinator'),
        ('Senior Administrative Services Officer', 'Senior Administrative Services Officer'),
        ('Senior Executive Assistant', 'Senior Executive Assistant'),
        ('Senior Special Events Coordinator', 'Senior Special Events Coordinator'),
        ('Senior Support Assistant', 'Senior Support Assistant'),
        ('Senior Support Specialist', 'Senior Support Specialist'),
        ('Special Events Coordinator', 'Special Events Coordinator'),
        ('Special Programs Coordinator', 'Special Programs Coordinator')
    )
    job_title = forms.ChoiceField(choices=CHOICES)


class BankingForm(forms.Form):
    CHOICES = (
        ('Agricultural Lender', 'Agricultural Lender'),
        ('Analyst, Bankruptcy Support', 'Analyst, Bankruptcy Support'),
        ('Anti-Money Laundering Auditor', 'Anti-Money Laundering Auditor'),
        ('Assistant Branch Manager', 'Assistant Branch Manager'),
        ('Assistant Trust Administrator', 'Assistant Trust Administrator'),
        ('Audit Manager', 'Audit Manager'),
        ('Bank Examiner', 'Bank Examiner'),
        ('Bankruptcy/Foreclosure Coordinator', 'Bankruptcy/Foreclosure Coordinator'),
        ('Bilingual Client Services Representative', 'Bilingual Client Services Representative'),
        ('Business Banking Loan Administration Manager', 'Business Banking Loan Administration Manager'),
        ('Business Banking Officer', 'Business Banking Officer'),
        ('Business Intelligence Manager', 'Business Intelligence Manager'),
        ('Client Service Manager', 'Client Service Manager'),
        ('Commercial Relationship Management Assistant', 'Commercial Relationship Management Assistant'),
        ('Common Trust Fund Accountant', 'Common Trust Fund Accountant'),
        ('Consumer Credit Analyst', 'Consumer Credit Analyst'),
        ('Consumer Finance Assistant Manager', 'Consumer Finance Assistant Manager'),
        ('Consumer Loans Processor', 'Consumer Loans Processor'),
        ('Consumer Loan Underwriter', 'Consumer Loan Underwriter'),
        ('Custody Investment Specialist', 'Custody Investment Specialist'),
        ('Customer Service Representative', 'Customer Service Representative'),
        ('Default Specialist', 'Default Specialist'),
        ('Escrow Manager', 'Escrow Manager'),
        ('eServices Quality Analyst', 'eServices Quality Analyst'),
        ('Head Teller', 'Head Teller'),
        ('Internal Auditor', 'Internal Auditor'),
        ('Investment Accounting Analyst', 'Investment Accounting Analyst'),
        ('Investment Management Operations Analyst', 'Investment Management Operations Analyst'),
        ('Investment Management Specialist', 'Investment Management Specialist'),
        ('Investment Planner', 'Investment Planner'),
        ('Junior Analyst - Asset Management', 'Junior Analyst - Asset Management'),
        ('Lead Business Consultant, Banking Innovation Center', 'Lead Business Consultant, Banking Innovation Center'),
        ('Lead Syndication Specialist', 'Lead Syndication Specialist'),
        ('Lending Manager', 'Lending Manager'),
        ('Loan Officer Trainee', 'Loan Officer Trainee'),
        ('Loan Representative', 'Loan Representative'),
        ('Loan Support Specialist', 'Loan Support Specialist'),
        ('Lock Box Clerk', 'Lock Box Clerk'),
        ('Loss Recovery Manager', 'Loss Recovery Manager'),
        ('Mortgage Consultant', 'Mortgage Consultant'),
        ('Mortgage Operations Support Technician', 'Mortgage Operations Support Technician'),
        ('New Accounts Banker', 'New Accounts Banker'),
        ('Online Customer Service Representative', 'Online Customer Service Representative'),
        ('Origination Loan Officer', 'Origination Loan Officer'),
        ('Personal Banker', 'Personal Banker'),
        ('Phone Banker', 'Phone Banker'),
        ('Premier Banker', 'Premier Banker'),
        ('Regulatory Compliance Analyst', 'Regulatory Compliance Analyst'),
        ('Relationship Manager, Commercial Lending', 'Relationship Manager, Commercial Lending'),
        ('Senior Financial Analyst', 'Senior Financial Analyst'),
        ('Senior Investment Analyst', 'Senior Investment Analyst'),
        ('Senior Teller', 'Senior Teller'),
        ('Senior Trust Consultant', 'Senior Trust Consultant'),
        ('Technology Risk Manager', 'Technology Risk Manager'),
        ('Trust Asset Manager', 'Trust Asset Manager'),
        ('Trust Assistant', 'Trust Assistant'),
        ('Wire Department Manager', 'Wire Department Manager'),

    )
    job_title = forms.ChoiceField(choices=CHOICES)


class ConsultingForm(forms.Form):
    CHOICES = (
        ('Environmental Consultant', 'Environmental Consultant'),
        ('Environmental Field Consultant', 'Environmental Field Consultant'),
        ('Environmental Project Manager', 'Environmental Project Manager'),
        ('Environmental Air Quality Consultant', 'Environmental Air Quality Consultant'),
        ('Environmental Audit Consultant', 'Environmental Audit Consultant'),
        ('Economic Consultant', 'Economic Consultant'),
        ('Financial Consultant', 'Financial Consultant'),
        ('Foreclosure Consultant', 'Foreclosure Consultant'),
        ('Fundraising Consultant', 'Fundraising Consultant'),
        ('Compensation Consultant', 'Compensation Consultant'),
        ('Compensation Survey Analyst', 'Compensation Survey Analyst'),
        ('Consultant, Federal Health', 'Consultant, Federal Health'),
        ('Consultant - Human Services', 'Consultant - Human Services'),
        ('Consultant Employment Specialist', 'Consultant Employment Specialist'),
        ('Healthcare Change Capture Senior Staff Consultant', 'Healthcare Change Capture Senior Staff Consultant'),
        ('Healthcare Consultant', 'Healthcare Consultant'),
        ('Healthcare Management Consultant', 'Healthcare Management Consultant'),
        ('Healthcare Market Research Consultant', 'Healthcare Market Research Consultant'),
        ('Human Capital Consultant', 'Human Capital Consultant'),
        ('Human Resources Consultant', 'Human Resources Consultant'),
        ('Recruitment Consultant', 'Recruitment Consultant'),
        ('Senior Benefits Consultant', 'Senior Benefits Consultant'),
        ('Staffing and Employee Relations Consultant', 'Staffing and Employee Relations Consultant'),
        ('Cyber Security Strategy Consultant', 'Cyber Security Strategy Consultant'),
        ('Dynamics AX - Functional Consultant', 'Dynamics AX - Functional Consultant'),
        ('Field Technical Consultant', 'Field Technical Consultant'),
        ('Sap Security Consultant', 'Sap Security Consultant'),
        ('Software Implementation Consultant', 'Software Implementation Consultant'),
        ('Senior Lync Consultant', 'Senior Lync Consultant'),
        ('Technology Consultant', 'Technology Consultant'),
        ('Telecom Analyst', 'Telecom Analyst'),
        ('Websphere Consultant', 'Websphere Consultant'),
        ('Business Consultant', 'Business Consultant'),
        ('Change Management Consultant', 'Change Management Consultant'),
        ('Principal Consultant - Infrastructure', 'Principal Consultant - Infrastructure'),
        ('Political Campaign Consultant', 'Political Campaign Consultant'),
        ('Political Consultant', 'Political Consultant'),
        ('Project Manager', 'Project Manager'),
        ('Senior Risk Control Consultant', 'Senior Risk Control Consultant'),
        ('Lactation Consultant', 'Lactation Consultant'),
        ('Life Coach', 'Life Coach'),
        ('Wedding Consultant', 'Wedding Consultant'),
        ('Weight Loss Consultant', 'Weight Loss Consultant'),
        ('Research Assistant', 'Research Assistant'),
        ('Business Analyst', 'Business Analyst'),
        ('Consulting Advisor', 'Consulting Advisor'),
        ('Creative Consultant', 'Creative Consultant'),
        ('Educational Consultant', 'Educational Consultant'),
        ('Government Contract Consultant', 'Government Contract Consultant'),
        ('Implementation Consultant', 'Implementation Consultant'),
        ('International Consultant', 'International Consultant'),
        ('Lead Consulting Engineer', 'Lead Consulting Engineer'),
        ('Management Consultant', 'Management Consultant'),
        ('Organizational Development Consultant', 'Organizational Development Consultant'),
        ('Political Strategist', 'Political Strategist'),
        ('Strategy Consultant', 'Strategy Consultant'),

    )
    job_title = forms.ChoiceField(choices=CHOICES)


class CorporateForm(forms.Form):
    CHOICES = (
        ('Chief Executive Officer ', 'Chief Executive Officer '),
        ('Chief Financial Officer', 'Chief Financial Officer'),
        ('Chief Operations Officers', 'Chief Operations Officers'),
        ('Chief Accounting Officer', 'Chief Accounting Officer'),
        ('Chief Applications Architect', 'Chief Applications Architect'),
        ('Chief Administrative Officer', 'Chief Administrative Officer'),
        ('Chief Contracting Officer', 'Chief Contracting Officer'),
        ('Chief Data Officer', 'Chief Data Officer'),
        ('Chief Development Officer', 'Chief Development Officer'),
        ('Chief Executive Officer', 'Chief Executive Officer'),
        ('Chief Compliance Officer', 'Chief Compliance Officer'),
        ('Chief Information Security Officer', 'Chief Information Security Officer'),
        ('Chief Information Officer', 'Chief Information Officer'),
        ('Chief Investments Officer', 'Chief Investments Officer'),
        ('Chief Information Technology Officer', 'Chief Information Technology Officer'),
        ('Chief Marketing Officer', 'Chief Marketing Officer'),
        ('Chief Product Officer', 'Chief Product Officer'),
        ('Chief Risk Officer', '(Chief Risk Officer'),
        ('Chief Security Officer', 'Chief Security Officer'),
        ('Chief Technical Officer', 'Chief Technical Officer'),
        ('Chief Underwriting Officer', 'Chief Underwriting Officer'),
        ('Chief Operating Officer', 'Chief Operating Officer'),
        ('Chief Operations Officer', 'Chief Operations Officer'),
        ('Chief Procurement Officer', 'Chief Procurement Officer'),

    )
    job_title = forms.ChoiceField(choices=CHOICES)


class HumanResourceseForm(forms.Form):
    CHOICES = (
        ('1st Shift HR Representative', '1st Shift HR Representative'),
        ('Administrative Assistant', 'Administrative Assistant'),
        ('Administrative Manager', 'Administrative Manager'),
        ('Applications Specialist​', 'Applications Specialist​'),
        ('Assistant Director, Employment', 'Assistant Director, Employment'),
        ('Assistant Director - Benefits', 'Assistant Director - Benefits'),
        ('Assistant Director of Human Resources', 'Assistant Director of Human Resources'),
        ('Assistant HR Manager', 'Assistant HR Manager'),
        ('Assistant VP of Human Resources', 'Assistant VP of Human Resources'),
        ('Associate Director of Human Resources', 'Associate Director of Human Resources'),
        ('Attorney', 'Attorney'),
        ('Benefits Administrator', 'Benefits Administrator'),
        ('Benefits and Work Comp Manager', 'Benefits and Work Comp Manager'),
        ('Benefits Coordinator', 'Benefits Coordinator'),
        ('Benefits Counselor', 'Benefits Counselor'),
        ('Benefits Specialist', 'Benefits Specialist'),
        ('Benefits Officer', 'Benefits Officer'),
        ('Category Manager, HR', 'Category Manager, HR'),
        ('Chief Happiness Officer', 'Chief Happiness Officer'),
        ('Chief Human Resources Officer', 'Chief Human Resources Officer'),
        ('Chief People Officer', 'Chief People Officer'),
        ('Client Facing Human Resources Specialist', 'Client Facing Human Resources Specialist'),
        ('Compensation Analyst', 'Compensation Analyst'),
        ('Contract Recruiter', 'Contract Recruiter'),
        ('Coordinator, Administrative Services', 'Coordinator, Administrative Services'),
        ('Coordinator, Talent Acquisition', 'Coordinator, Talent Acquisition'),
        ('Director of Employment', 'Director of Employment'),
        ('Director of Employment and Recruiting', 'Director of Employment and Recruiting'),
        ('Director of Employment Services', 'Director of Employment Services'),
        ('Director of Talent', 'Director of Talent'),
        ('Director of Talent Management', 'Director of Talent Management'),
        ('District Human Resources Manager', 'District Human Resources Manager'),
        ('eCommerce Recruiter - HR Coordinator', 'eCommerce Recruiter - HR Coordinator'),
        ('E-Learning Analyst', 'E-Learning Analyst'),
        ('E-Learning Coordinator', 'E-Learning Coordinator'),
        ('E-Learning Director', 'E-Learning Director'),
        ('E-Learning Executive Director', 'E-Learning Executive Director'),
        ('E-Learning Manager', 'E-Learning Manager'),
        ('E-Learning Specialist', 'E-Learning Specialist'),
        ('Employee Relations Leader', 'Employee Relations Leader'),
        ('Employment Supervisor', 'Employment Supervisor'),
        ('Employment Supervisor', 'Employment Supervisor'),
        ('Employee and Labor Relations Consultant', 'Employee and Labor Relations Consultant'),
        ('Employee Benefits Account Manager', 'Employee Benefits Account Manager'),
        ('Employee Benefits Law Specialist', 'Employee Benefits Law Specialist'),
        ('Employee Relations Associate Counsel', 'Employee Relations Associate Counsel'),
        ('Employee Relations Consultant', 'Employee Relations Consultant'),
        ('Employee Relations Manager', 'Employee Relations Manager'),
        ('Employee Relations Specialist', 'Employee Relations Specialist'),
        ('Employee Retention Manager', 'Employee Retention Manager'),
        ('Employment Law Specialist', 'Employment Law Specialist'),
        ('Functional Leader', 'Functional Leader'),
        ('HRIS Manager', 'HRIS Manager'),
        ('HR Manager Multi-site', 'HR Manager Multi-site'),
        ('Human Resources Administrator', 'Human Resources Administrator'),
        ('Human Resources Advocate', 'Human Resources Advocate'),
        ('Human Resources Adviser', 'Human Resources Adviser'),
        ('Human Resources Analyst', 'Human Resources Analyst'),
        ('Human Resources and Safety Coordinator', 'Human Resources and Safety Coordinator'),
        ('Human Resources Assistant', 'Human Resources Assistant'),
        ('Human Resources Associate', 'Human Resources Associate'),
        ('Human Resources Business Partner', 'Human Resources Business Partner'),
        ('Human Resources Champion', 'Human Resources Champion'),
        ('Human Resources Clerk', 'Human Resources Clerk'),
        ('Human Resources Coach', 'Human Resources Coach'),
        ('Human Resources Consultant', 'Human Resources Consultant'),
        ('Human Resources Compensation Coordinator', 'Human Resources Compensation Coordinator'),
        ('Human Resources Coordinator', 'Human Resources Coordinator'),
        ('Human Resources Representative', 'Human Resources Representative'),
        ('Human Resources Specialist', 'Human Resources Specialist'),
        ('Job Posting Specialist', 'Job Posting Specialist'),
        ('Manager IS Risk and Compliance', 'Manager IS Risk and Compliance'),
        ('Manager of Career and Employee Relations', 'Manager of Career and Employee Relations'),
        ('Organizational Development Specialist', 'Organizational Development Specialist'),
        ('Organizational Development Administrator', 'Organizational Development Administrator'),
        ('Organizational Development Analyst', 'Organizational Development Analyst'),
        ('Organizational Development Manager', 'Organizational Development Manager'),
        ('Organizational Development Director', 'Organizational Development Director'),
        ('Organizational Development VP', 'Organizational Development VP'),
        ('Payroll Processing Specialist', 'Payroll Processing Specialist'),
        ('Plant Human Resources Manager', 'Plant Human Resources Manager'),
        ('Recruiter', 'Recruiter'),
        ('Retirement Plan Counselor', 'Retirement Plan Counselor'),
        ('Safety Compliance and Recruitment Specialist', 'Safety Compliance and Recruitment Specialist'),
        ('Safety Coordinator', 'Safety Coordinator'),
        ('Senior Employee Benefits Consultant', 'Senior Employee Benefits Consultant'),
        ('Talent Acquisition Manager', 'Talent Acquisition Manager'),
        ('Technical Recruiter', 'Technical Recruiter'),
        ('Trainer', 'Trainer'),
        ('Training Coordinator', 'Training Coordinator'),
        ('Union Organizer', 'Union Organizer'),
        ('Vice President of Diversity', 'Vice President of Diversity'),
        ('Vice President of Human Resources', 'Vice President of Human Resources'),
        ('Vice President of People', 'Vice President of People'),
        ('Website Content Administrator', 'Website Content Administrator')

    )
    job_title = forms.ChoiceField(choices=CHOICES)


class InsuranceForm(forms.Form):
    CHOICES = (
        ('Actuarial Analyst', 'Actuarial Analyst'),
        ('Actuarial Associate', 'Actuarial Associate'),
        ('Actuarial Manager', 'Actuarial Manager'),
        ('Actuary', 'Actuary'),
        ('Adjuster', 'Adjuster'),
        ('Claims Adjuster', 'Claims Adjuster'),
        ('Claims Analyst', 'Claims Analyst'),
        ('Claims Examiner', 'Claims Examiner'),
        ('Claims Manager', 'Claims Manager'),
        ('Claims Representative', 'Claims Representative'),
        ('Claims Specialist', 'Claims Specialist'),
        ('Claims Clerk', 'Claims Clerk'),
        ('Estimator', 'Estimator'),
        ('Examiner', 'Examiner'),
        ('Field Adjuster', 'Field Adjuster'),
        ('Clerk', 'Clerk'),
        ('Administrative Assistant', 'Administrative Assistant'),
        ('Bookkeeper', 'Bookkeeper'),
        ('Policy Processing Clerk', 'Policy Processing Clerk'),
        ('Customer Service Associate', 'Customer Service Associate'),
        ('Customer Service Representative', 'Customer Service Representative'),
        ('Customer Service Manager', 'Customer Service Manager'),
        ('Sales Agency Manager', 'Sales Agency Manager'),
        ('Sales Agent', 'Sales Agent'),
        ('State Sales Manager', 'State Sales Manager'),
        ('Loss Control Consultant/Specialist', 'Loss Control Consultant/Specialist'),
        ('Risk Consultant', 'Risk Consultant'),

    )
    job_title = forms.ChoiceField(choices=CHOICES)


class InternationalBusinessForm(forms.Form):
    CHOICES = (
        ('Business Development Associate', 'Business Development Associate'),
        ('Director of International Growth', 'Director of International Growth'),
        ('Global Business Administrator', 'Global Business Administrator'),
        ('Global Business Analysis Director', 'Global Business Analysis Director'),
        ('International Business Analyst', 'International Business Analyst'),
        ('International Business Development Director', 'International Business Development Director'),
        ('International Business Operations Associate', 'International Business Operations Associate'),
        ('International Business Specialist', 'International Business Specialist'),
        ('Junior Business Development Manager', 'Junior Business Development Manager'),
        ('Manager, International Business Development', 'Manager, International Business Development'),
        ('Middle East Business Development Manager', 'Middle East Business Development Manager'),
        ('Asia Regional Representative', 'Asia Regional Representative'),
        ('Country Director', 'Country Director'),
        ('Development Assistant', 'Development Assistant'),
        ('Development Associate', 'Development Associate'),
        ('Economic Development Specialist', 'Economic Development Specialist'),
        ('Economic Security Delegate', 'Economic Security Delegate'),
        ('Education Specialist', 'Education Specialist'),
        ('Emergency Health Program Coordinator', 'Emergency Health Program Coordinator'),
        ('Emergency Response Coordinator', 'Emergency Response Coordinator'),
        ('Family Planning Adviser', 'Family Planning Adviser'),
        ('Fellow, Energy', 'Fellow, Energy'),
        ('Finance Director', 'Finance Director'),
        ('Food Security Analyst', 'Food Security Analyst'),
        ('Global Relations Officer', 'Global Relations Officer'),
        ('Grants and Compliance Manager', 'Grants and Compliance Manager'),
        ('Head of Mission', 'Head of Mission'),
        ('Human Dimension Officer', 'Human Dimension Officer'),
        ('Humanitarian Program Manager', 'Humanitarian Program Manager'),
        ('Red Cross Country Representative', 'Red Cross Country Representative'),
        ('Research Associate, Africa', 'Research Associate, Africa'),
        ('Response Team Leader', 'Response Team Leader'),
        ('Senior Crisis Adviser', 'Senior Crisis Adviser'),
        ('International Claims Manager ', 'International Claims Manager '),
        ('International Assignment Specialist', 'International Assignment Specialist'),
        ('International Retirement Leader', 'International Retirement Leader'),
        ('Counterintelligence Officer', 'Counterintelligence Officer'),
        ('Director of Policy', 'Director of Policy'),
        ('Foreign Affairs Specialist', 'Foreign Affairs Specialist'),
        ('Foreign Policy Advisor', 'Foreign Policy Advisor'),
        ('Foreign Service Officer', 'Foreign Service Officer'),
        ('Intelligence Analyst', 'Intelligence Analyst'),
        ('Policy Analyst', 'Policy Analyst'),
        ('Political Affairs Officer', 'Political Affairs Officer'),
        ('Program Assistant', 'Program Assistant'),
        ('Chief of Party', 'Chief of Party'),
        ('Controller', 'Controller'),
        ('International Division Project Coordinator', 'International Division Project Coordinator'),
        ('International Management Consultant', 'International Management Consultant'),
        ('International Retail Operations Consulting Manager', 'International Retail Operations Consulting Manager'),
        ('Multinational Manager', 'Multinational Manager'),
        ('Operations Analyst', 'Operations Analyst'),
        ('Partnership Analyst', 'Partnership Analyst'),
        ('Project Manager', 'Project Manager'),
        ('Communications Officer', 'Communications Officer'),
        ('Events Manager', 'Events Manager'),
        ('Global Internal Communication Specialist', 'Global Internal Communication Specialist'),
        ('Lead Proposal Writer', 'Lead Proposal Writer'),

    )
    job_title = forms.ChoiceField(choices=CHOICES)


class LegalForm(forms.Form):
    CHOICES = (
        ('Administrative assistant', 'Administrative assistant'),
        ('Clerk', 'Clerk'),
        ('Copy center professional', 'Copy center professional'),
        ('Document coder', 'Document coder'),
        ('File clerk', 'File clerk'),
        ('Legal aide/assistant', 'Legal aide/assistant'),
        ('Legal secretary', 'Legal secretary'),
        ('Mailroom personnel', 'Mailroom personnel'),
        ('Legal records manager', 'Legal records manager'),
        ('Contract administrator', 'Contract administrator'),
        ('Contract analyst', 'Contract analyst'),
        ('Contract drafting legal specialist', 'Contract drafting legal specialist'),
        ('Consultant', 'Consultant'),
        ('Regulatory affairs director', 'Regulatory affairs director'),
        ('Right of way agent', 'Right of way agent'),
        ('Software consultant', 'Software consultant'),
    )
    job_title = forms.ChoiceField(choices=CHOICES)


class PublicRelationsForm(forms.Form):
    CHOICES = (
        ('Brand Ambassador', 'Brand Ambassador'),
        ('Chapter Relations Administrator', 'Chapter Relations Administrator'),
        ('Content Manager', 'Content Manager'),
        ('Content Strategist', 'Content Strategist'),
        ('Copy Writer', 'Copy Writer'),
        ('Director of Public Affairs', 'Director of Public Affairs'),
        ('Director of Public Relations', 'Director of Public Relations'),
        ('Editor', 'Editor'),
        ('Executive Assistant', 'Executive Assistant'),
        ('Event Coordinator', 'Event Coordinator'),
        ('Event Manager', 'Event Manager'),
        ('Lobbyist', 'Lobbyist'),
        ('Manager', 'Manager'),
        ('Manager, Digital and Social Media', 'Manager, Digital and Social Media'),
        ('Managing Editor', 'Managing Editor'),
        ('Media Director', 'Media Director'),
        ('New Media Coordinator', 'New Media Coordinator'),
        ('Program Coordinator', 'Program Coordinator'),
        ('Public Affairs Manager', 'Public Affairs Manager'),
        ('Public Affairs Specialist', 'Public Affairs Specialist'),
        ('Public Information Assistant', 'Public Information Assistant'),
        ('Public Information Officer', 'Public Information Officer'),
        ('Public Information Specialist', 'Public Information Specialist'),
        ('Public Relations Coordinator', 'Public Relations Coordinator'),
        ('Public Relations Director', 'Public Relations Director'),
        ('Public Relations Manager', 'Public Relations Manager'),
        ('Public Relations Specialist', 'Public Relations Specialist'),
        ('Publicist', 'Publicist'),
        ('Relationship Manager', 'Relationship Manager'),
        ('Social Media Analyst', 'Social Media Analyst'),
        ('Social Media Specialist', 'Social Media Specialist'),
        ('Technical Writer', 'Technical Writer'),
        ('Account Director', 'Account Director'),
        ('Account Executive', 'Account Executive'),
        ('Account Manager', 'Account Manager'),
        ('Account Supervisor', 'Account Supervisor'),
        ('Senior Account Executive', 'Senior Account Executive'),
        ('Communications Coordinator', 'Communications Coordinator'),
        ('Communications Director', 'Communications Director'),
        ('Communications Editor', 'Communications Editor'),
        ('Communications Representative', 'Communications Representative'),
        ('Corporate Communications Specialist', 'Corporate Communications Specialist'),
        ('Director of Communications', 'Director of Communications'),
        ('Director of Strategic Communication', 'Director of Strategic Communication'),
        ('External Communications Manager', 'External Communications Manager'),
        ('Internal Communications Specialist', 'Internal Communications Specialist'),
        ('Marketing Communications Director', 'Marketing Communications Director'),
        ('Marketing Communications Manager', 'Marketing Communications Manager'),
        ('Development Director', 'Development Director'),
        ('Development Officer', 'Development Officer'),
        ('Director of Development', 'Director of Development'),
        ('Financial Public Relations Associate', 'Financial Public Relations Associate'),
        ('Fundraising Manager', 'Fundraising Manager'),
        ('Marketing Associate', 'Marketing Associate'),
        ('Marketing Communications Director', 'Marketing Communications Director'),
        ('Marketing Communications Manager', 'Marketing Communications Manager'),
        ('Marketing Coordinator', 'Marketing Coordinator'),
        ('Marketing Officer', 'Marketing Officer'),
        ('Social Media Marketing Coordinator', 'Social Media Marketing Coordinator'),
        ('Manager, Digital and Social Media', 'Manager, Digital and Social Media'),
        ('Media and Communications Manager', 'Media and Communications Manager'),
        ('Media Coordinator', 'Media Coordinator'),
        ('Media Director', 'Media Director'),
        ('Media Relations Manager', 'Media Relations Manager'),
        ('New Media Coordinator', 'New Media Coordinator'),
        ('Social Media Specialist', 'Social Media Specialist'),
    )
    job_title = forms.ChoiceField(choices=CHOICES)


class PurchasingForm(forms.Form):
    CHOICES = (
        ('Buyer', 'Buyer'),
        ('Commodity Manager', 'Commodity Manager'),
        ('Procurement Director', 'Procurement Director'),
        ('Procurement Officer', 'Procurement Officer'),
        ('Strategic Sourcing Director', 'Strategic Sourcing Director'),
        ('Purchasing Agent', 'Purchasing Agent'),
        ('Materials Manager', 'Materials Manager'),
        ('Purchasing Director', 'Purchasing Director'),
        ('Category Purchasing Manager', 'Category Purchasing Manager'),
        ('Materials Director', 'Materials Director'),
        ('Procurement Manager', 'Procurement Manager'),
        ('Purchasing Supervisor', 'Purchasing Supervisor'),
        ('Procurement Assistant', 'Procurement Assistant'),
        ('Procurement Officer', 'Procurement Officer'),
        ('Procurement Technician', 'Procurement Technician'),
        ('Purchasing Associate', 'Purchasing Associate'),
        ('Purchasing Specialist', 'Purchasing Specialist'),
        ('Warehouse Clerk', 'Warehouse Clerk'),
        ('Logistics Team Lead', 'Logistics Team Lead'),
        ('Client Services Administrator', 'Client Services Administrator'),
        ('Logistic Vice President', 'Logistic Vice President'),
        ('Production Planner', 'Production Planner'),
        ('Supportability Engineer', 'Supportability Engineer'),
        ('General Manager', 'General Manager'),
        ('Plant Manager', 'Plant Manager'),
        ('Facilities Manager', 'Facilities Manager'),
        ('Plant Superintendent', 'Plant Superintendent'),

    )
    job_title = forms.ChoiceField(choices=CHOICES)


class SalesForm(forms.Form):
    CHOICES = (
        ('Account Representative', 'Account Representative'),
        ('Advertising Sales Representative', 'Advertising Sales Representative'),
        ('Automotive Sales Representative', 'Automotive Sales Representative'),
        ('B2B Corporate Sales', 'B2B Corporate Sales'),
        ('Brand Ambassador', 'Brand Ambassador'),
        ('Customer Care Representative', 'Customer Care Representative'),
        ('Direct Salesperson', 'Direct Salesperson'),
        ('Distribution Sales Representative', 'Distribution Sales Representative'),
        ('Enterprise Sales Representative', 'Enterprise Sales Representative'),
        ('Equipment Sales Representative', 'Equipment Sales Representative'),
        ('Equipment Sales Specialist', 'Equipment Sales Specialist'),
        ('Healthcare Sales Representative', 'Healthcare Sales Representative'),
        ('Industrial Sales Representative', 'Industrial Sales Representative'),
        ('Inside Salesperson', 'Inside Salesperson'),
        ('Insurance Sales Representative', 'Insurance Sales Representative'),
        ('Medical Sales Representative', 'Medical Sales Representative'),
        ('National Accounts Sales Representative', 'National Accounts Sales Representative'),
        ('Outside Sales Representative', 'Outside Sales Representative'),
        ('Retail Sales Representative', 'Retail Sales Representative'),
        ('Route Sales Representative', 'Route Sales Representative'),
        ('Sales Assistant', 'Sales Assistant'),
        ('Sales Trainee', 'Sales Trainee'),
        ('Specialty Sales Representative', 'Specialty Sales Representative'),
        ('Territory Sales Representative', 'Territory Sales Representative'),
        ('Franchise Development Manager', 'Franchise Development Manager'),
        ('Group Sales Manager', 'Group Sales Manager'),
        ('Manager, Business Development', 'Manager, Business Development'),
        ('Marketing Manager', 'Marketing Manager'),
        ('National Sales Manager', 'National Sales Manager'),
        ('Regional Manager', 'Regional Manager'),
        ('Regional Sales Manager', 'Regional Sales Manager'),
        ('Retail Store Manager', 'Retail Store Manager'),
        ('Sales Manager', 'Sales Manager'),
        ('Wholesale Sales Manager', 'Wholesale Sales Manager'),
        ('Group and Events Sales Coordinator', 'Group and Events Sales Coordinator'),
        ('Key Account Manager', 'Key Account Manager'),
        ('Major Accounts Manager', 'Major Accounts Manager'),
        ('Director of Inside Sales', 'Director of Inside Sales'),
        ('Director of National Sales', 'Director of National Sales'),
        ('Director of Sales', 'Director of Sales'),
    )

    job_title = forms.ChoiceField(choices=CHOICES)
