# Generated by Django 3.0.8 on 2020-09-29 20:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='WorkTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_work', models.TimeField(blank=True, null=True)),
                ('end_work', models.TimeField(default=None)),
                ('hours_in_day', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('start_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('end_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('date', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Worktimes.Date')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Employees.Employee')),
            ],
        ),
    ]
