# Generated by Django 3.0.8 on 2020-10-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Worktimes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktime',
            name='end_work',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
